@startuml ModeloDeDominio

skin rose
left to right direction

object LNDLP 

object Marketing 
object TourManager 
object Visual 
object Agency 

LNDLP -- "1" Marketing
LNDLP -- "1" TourManager
LNDLP -- "1" Visual
LNDLP -- "1" Agency

object Artista{
    nombre
    descripcion
    ciudad
}

TourManager *-- "*" Artista

object RedSocial{
    instagram
}
object Cancion{
    titulo
}
object Album{
    titulo
    portada
}
object Festival{
    fecha 
    ciudad
}
object Concierto{
    fecha 
    entradas
}

Artista *-- "*" RedSocial
Artista *-- "*" Cancion
Artista *-- "*" Album
Artista *-- "*" Festival
Artista *-- "*" Concierto

object Videoclip

Visual *-- "*" Videoclip


object Empresa
LNDLP -right- "*" Empresa

@enduml
