@startuml presentacion
skin rose
skinparam linetype polyline

title Controladores - Empresa

class EmpresaControlador {
    private ICompanyService _companyService;
    GetCompanyByType(string type)
    GetCompanyIntranet([FromQuery] PaginationFilter paginationFilter)
    PostFilterCompanyIntranet([FromQuery] PaginationFilter paginationFilter, [FromBody] List<Filter> filters)
}
@enduml
