@startuml presentacion
skin rose
skinparam linetype polyline

title Controladores - Festival

class FestivalControlador {
    private readonly IFestivalService _festivalService;
    GetFestivalIntranet([FromQuery] PaginationFilter paginationFilter)
    GetFestivalIntranet([FromQuery] PaginationFilter paginationFilter, [FromBody] List<Filter> filters)
    GetFutureFestivales()
}
@enduml