@startuml tryhtr
skin rose 

skinparam {
    NoteBackgroundColor #whiteSmoke
    ArrowColor #green
    NoteBorderColor #blue
    linetype polyline
}


hide empty description

state initstate as "INICIO"
state iniciar_sesion
state openDashboard as ":abrir_backoffice"
state endstate as "BACKOFFICE_ABIERTO"

initstate --> iniciar_sesion
note on link
<b>El usuario solicita</b>
* iniciar_sesion
end note

state iniciar_sesion {

    state 1 as " "
    state 2 as " "
    state condicional <<choice>>

    [*] --> 1

    1 --> 2
    note on link
    <b>El sistema requiere</b>
    * usuario
    * contraseña
    end note

    2 --> condicional
    note on link
    <b>El usuario proporciona</b>
    * usuario
    * contraseña
    end note

    condicional -[#red]-> 1
    note on link
    [usuario o contraseña incorrectos]
    end note

    condicional --> [*]
}

iniciar_sesion  --> openDashboard

openDashboard --> endstate

@enduml
