@startuml CasoDeUsoWeb

skin rose

left to right direction
actor "Visitor" as vi

:Visual: as V
:Admin: as A
:Crew: as C
:Visitor: as vi

vi <|-up- V
vi <|-up- C
vi <|-up- A


package PaginaWeb {
    usecase "Iniciar sesion" as UC1
    usecase "Leer artistas que trabajan con LNDLP" as UC2
    usecase "Leer próximos conciertos" as UC3
    usecase "Leer próximos festivales" as UC4
    usecase "Contactas con LNDLP" as UC5
    usecase "Leer videoclips de LNDLP" as UC6
    usecase "Leer artistas que trabajan con LNDLP" as UC7
    usecase "Leer detalles del artista" as UC8
    usecase "Leer albumes del artista" as UC9
    usecase "Leer canciones del artista" as UC10
    usecase "Leer próximos conciertos del artista" as UC11
    usecase "Leer empresas (sellos) que trabajan con LNDLP" as UC12
    usecase "Leer empresas (partners) que trabajan con LNDLP" as UC13
    usecase "Leer empresas (marcas) que trabajan con LNDLP" as UC14
    usecase "Leer empresas (proyectos) que trabajan con LNDLP" as UC15
    usecase "Cerrar sesiion" as UC16
    
    vi --> UC2
    vi --> UC3
    vi --> UC4
    vi --> UC5
    vi --> UC6
    vi --> UC7
    vi --> UC12
    vi --> UC13
    vi --> UC14
    vi --> UC15

    UC7 .-> UC8: <<extends>>
    UC7 .-> UC9: <<extends>>
    UC7 .-> UC10: <<extends>>
    UC7 .-> UC11: <<extends>>

    UC1 .-> UC16: <<extends>>

    V --> UC1
    A --> UC1
    C --> UC1

}

@enduml