@startuml CasosDeUsoAdmin

skin rose
left to right direction
:Admin: as A

package BackOfficeAdminArtista {

    (Leer artistas) .-> (Crear artista): <<extend>>
    (Leer artistas) .-> (Editar artista): <<extend>>
    (Leer artistas) .-> (Eliminar artista): <<extend>>
    (Leer artistas) .-> (Leer red social): <<extends>>

    (Leer usuarios) .-> (Crear usuario): <<extend>>
    (Leer usuarios) .-> (Editar usuario): <<extend>>
    (Leer usuarios) .-> (Eliminar usuario): <<extend>>

    (Leer red social) .-> (Editar red social): <<extend>>

    (Crear artista) .-> (Crear red social): <<include>>

    (Leer empresas) .-> (Editar empresa): <<extends>>
    (Leer empresas) .-> (Crear empresa): <<extends>>
    (Leer empresas) .-> (Eliminar empresa): <<extends>>
}


A --> (Leer artistas)
A --> (Leer empresas)
A --> (Leer usuarios)


@enduml