@startuml CasosDeUsoVisual

skin rose
left to right direction
:Visual: as V

package BackOfficeVisual {
    (Leer videoclips) .-> (Crear videoclip): <<extends>>
    (Leer videoclips) .-> (Eliminar videoclip): <<extends>>
    (Leer videoclips) .-> (Editar videoclip): <<extends>>
}

V --> (Leer videoclips) 
@enduml