@startuml presentacion
skin rose
skinparam linetype polyline
allow_mixing

package APIREST #e1eced{
    package CapaNegocio {
        package Controladores {
            class ArtistaControlador <<API>> <<@Path>> {
                + ARTISTAS : String ="/Artistas"
                void crearArtista(dto : artistaDto)
            }
        }
        package Servicios {
            interface IArtistaServicio {
                void crearArtista(dto : artistaDto)
            }
            class ArtistaServicio {
                void crearArtista(dto : artistaDto)
            }
        }
        package Repositorio {
            interface IArtistaRepositorio {
                void postArtistaAsync(Artista: artista)
            }
            class ArtistaRepositorio {
                void postArtistaAsync(Artista : artista)
            }
        }
    }

    package CapaTransferenciaDatos{
        package DTO {
            class ArtistaDto {
            }
        }
    }

    package CapaDatos {
        package Entidades {
            class Artista {
            }
        }
        package InterfacesEntidades{
            interface IHasPhotoUrl {
            }
        }
    }

    package CapaServicios{
        package Paginacion{
            class Pagination {
                void paginationEntity (array[] : filtros)
            }
        }
        package Filtros {
            class Filter {
                void filterEntity (array[] : filtros)
            }
        }
        package Mapeadores {
            class Mapper {
                void mapearArtistaDtoArtista (dto : ArtistaDto)
            }
        }
    }
}

ArtistaControlador --> IArtistaServicio
ArtistaControlador --> ArtistaDto
IArtistaServicio --|> ArtistaServicio
IArtistaServicio --|> ArtistaDto


ArtistaServicio --> IArtistaRepositorio
ArtistaServicio --> ArtistaDto
IArtistaRepositorio --|> ArtistaRepositorio

ArtistaServicio ..> Mapper

Mapper ..> ArtistaDto
Mapper ..> Artista

IHasPhotoUrl ..> Artista

@enduml
