@startuml presentacion
skin rose
skinparam linetype polyline

title Repositorios - Album

interface i as "IAlbumRepositorio"{
    GetAlbumsAsync(Expression<Func<Album, bool>> predicate)
}

class c as "AlbumRepositorio"{
    private readonly APIContext _context;
    GetAlbumsAsync(Expression<Func<Album, bool>> predicate)
}


i <|-- c
@enduml