@startuml presentacion
skin rose
skinparam linetype polyline

title Repositorios - Concierto

interface i as "IConciertoRepositorio"{
    GetConcertsAsync(Expression<Func<Concert, bool>> predicate)
    GetFutureConcertsAsync()
    GetConcertsForArtistAsync(Expression<Func<Concert, bool>> predicate, int id)
}

class c as "ConciertoRepositorio"{
    private readonly APIContext _context;
    GetConcertsAsync(Expression<Func<Concert, bool>> predicate)
    GetFutureConcertsAsync()
    GetConcertsForArtistAsync(Expression<Func<Concert, bool>> predicate, int id)
}


i <|-- c
@enduml