@startuml presentacion
skin rose
skinparam linetype polyline

title Repositorios - Empresa

interface i as "IEmpresaRepositorio"{
    GetCompaniesAsync(Expression<Func<Company, bool>> predicate)
    GetByTypeAsync(string type)
}

class c as "EmpresaRepositorio"{
    private readonly APIContext _context;
    GetCompaniesAsync(Expression<Func<Company, bool>> predicate)
    GetByTypeAsync(string type)
}


i <|-- c
@enduml