@startuml presentacion
skin rose
skinparam linetype polyline

title Repositorios - Usuario

interface i as "IUsuarioRepositorio"{
    GetUsersAsync(Expression<Func<User, bool>> predicate)
    ExistUserAsync(int idUser)
    ExistUserMailAsync(string userMail)
}

class c as "UsuarioRepositorio"{
    private readonly APIContext _context;
    GetUsersAsync(Expression<Func<User, bool>> predicate)
    ExistUserAsync(int idUser)
    ExistUserMailAsync(string userMail)
}


i <|-- c
@enduml