@startuml presentacion
skin rose
skinparam linetype polyline

title Repositorios - YoutubeVideo

interface i as "IYoutubeVideoRepositorio"{

}

class c as "YoutubeVideoRepositorio"{
    private readonly APIContext _context;

}


i <|-- c
@enduml