@startuml DiagramaContextoVisual

left to right direction
skin rose
skinparam {
    NoteBackgroundColor #whiteSmoke
    ArrowColor #green
    NoteBorderColor #blue
    linetype polyline
}
hide empty description

[*] -[#green]-> BACKOFFICE_ABIERTO

BACKOFFICE_ABIERTO -[#green]-> CONCIERTOS_ABIERTO
note on link 
  Leer conciertos
end note


BACKOFFICE_ABIERTO -[#green]-> FESTIVALES_ABIERTO
note on link 
  Leer festivales
end note


CONCIERTOS_ABIERTO -[#green]-> BACKOFFICE_ABIERTO
FESTIVALES_ABIERTO -[#green]-> BACKOFFICE_ABIERTO


CONCIERTOS_ABIERTO -[#green]-> [*]
note on link 
  Cerrar sesion
end note
FESTIVALES_ABIERTO -[#green]-> [*] 
note on link 
  Cerrar sesion
end note


@enduml