@startuml DiagramaContextoVisual

left to right direction
skin rose

skinparam {
    NoteBackgroundColor #whiteSmoke
    ArrowColor #green
    NoteBorderColor #blue
    linetype polyline
}
hide empty description

[*] -[#green]-> BACKOFFICE_ABIERTO

BACKOFFICE_ABIERTO -[#green]-> ARTISTAS_ABIERTO
note on link 
  Leer artistas
end note
BACKOFFICE_ABIERTO -[#green]-> CANCIONES_ABIERTO
note on link 
  Leer canciones
end note
BACKOFFICE_ABIERTO -[#green]-> ALBUMES_ABIERTO
note on link 
  Leer albumes
end note
BACKOFFICE_ABIERTO -[#green]-> CONCIERTOS_ABIERTO
note on link 
  Leer conciertos
end note
BACKOFFICE_ABIERTO -[#green]-> FESTIVALES_ABIERTO
note on link 
  Leer festivales
end note
BACKOFFICE_ABIERTO -[#green]-> USUARIOS_ABIERTO
note on link 
  Leer usuarios
end note
BACKOFFICE_ABIERTO -[#green]-> EMPRESAS_ABIERTO
note on link 
  Leer empresas
end note

ARTISTAS_ABIERTO -[#green]-> BACKOFFICE_ABIERTO
CANCIONES_ABIERTO -[#green]-> BACKOFFICE_ABIERTO
ALBUMES_ABIERTO -[#green]-> BACKOFFICE_ABIERTO
CONCIERTOS_ABIERTO -[#green]-> BACKOFFICE_ABIERTO
FESTIVALES_ABIERTO -[#green]-> BACKOFFICE_ABIERTO
USUARIOS_ABIERTO -[#green]-> BACKOFFICE_ABIERTO
EMPRESAS_ABIERTO -[#green]-> BACKOFFICE_ABIERTO


ARTISTAS_ABIERTO -[#green]-> ARTISTAS_ABIERTO
note on link 
  Crear artista
  Editar artista
  Eliminar artista
  Leer red social
  Editar red social
end note

CANCIONES_ABIERTO -[#green]-> CANCIONES_ABIERTO
note on link 
  Leer artistas
  Crear cancion
  Editar cancion
  Eliminar cancion
end note

ALBUMES_ABIERTO -[#green]-> ALBUMES_ABIERTO
note on link 
  Leer artistas
  Crear album
  Editar album
  Eliminar album
end note

CONCIERTOS_ABIERTO -[#green]-> CONCIERTOS_ABIERTO
note on link 
  Leer artistas
  Crear concierto
  Editar concierto
  Eliminar concierto
end note

FESTIVALES_ABIERTO -[#green]-> FESTIVALES_ABIERTO
note on link 
  Leer artistas
  Asociar artistas
  Crear festival
  Editar festival
  Eliminar festival
end note

USUARIOS_ABIERTO -[#green]-> USUARIOS_ABIERTO
note on link 
  Crear usuario
  Editar usuario
  Eliminar usuario
end note

EMPRESAS_ABIERTO -[#green]-> EMPRESAS_ABIERTO
note on link 
  Crear empresa
  Editar empresa
  Eliminar empresa
end note

ARTISTAS_ABIERTO -[#green]-> [*]
note on link 
  Cerrar sesion
end note
CANCIONES_ABIERTO -[#green]-> [*]
note on link 
  Cerrar sesion
end note
ALBUMES_ABIERTO -[#green]-> [*]
note on link 
  Cerrar sesion
end note
CONCIERTOS_ABIERTO -[#green]-> [*]
note on link 
  Cerrar sesion
end note
FESTIVALES_ABIERTO -[#green]-> [*]
note on link 
  Cerrar sesion
end note
USUARIOS_ABIERTO -[#green]-> [*]
note on link 
  Cerrar sesion
end note
EMPRESAS_ABIERTO -[#green]-> [*]
note on link 
  Cerrar sesion
end note

@enduml