@startuml crear_Entidad

skin rose
skinparam {
    NoteBorderThickness 0
    NoteBackgroundColor #whiteSmoke
    RectangleBackgroundColor #whiteSmoke
    ArchimateBackgroundColor #whiteSmoke
}


actor User
rectangle #3CBE2D EntidadVista
rectangle #629EF9 EntidadControlador
rectangle #C6480E EntidadServicio
rectangle #D269D2 EntidadRepositorio
rectangle #08EFF3 Entidad
rectangle #CDEBA5 "BACKOFFICE ABIERTO" as OpenDashboard

EntidadVista -left-> OpenDashboard
note on link
    entidad creada
end note

User --> EntidadVista
note on link
    crear entidad (entidad)
end note

EntidadVista --> EntidadControlador
note on link
    crear entidad (entidad)
end note

EntidadControlador --> EntidadServicio
note on link
    crear entidad (entidad)
end note

EntidadServicio --> EntidadRepositorio
note on link
    crear entidad (entidad)
end note

EntidadRepositorio --> Entidad
note on link
    crear entidad (entidad)
end note

Entidad --> EntidadRepositorio
note on link
    entidad creada
end note

EntidadRepositorio --> EntidadServicio
note on link
    entidad creada
end note


EntidadServicio --> EntidadControlador
note on link
    entidad creada
end note

EntidadControlador --> EntidadVista
note on link
    entidad creada
end note



@enduml
