@startuml crear_artista

skin rose
skinparam {
    NoteBorderThickness 0
    NoteBackgroundColor #whiteSmoke
    RectangleBackgroundColor #whiteSmoke
    ArchimateBackgroundColor #whiteSmoke
}


actor admin
rectangle #3CBE2D ArtistaVista
rectangle #629EF9 ArtistaControlador
rectangle #C6480E ArtistaServicio
rectangle #C6480E RedSocialServicio
rectangle #C6480E UsuarioServicio
rectangle #D269D2 ArtistaRepositorio
rectangle #D269D2 RedSocialRepositorio
rectangle #D269D2 UsuarioRepositorio
rectangle #08EFF3 Artista
rectangle #08EFF3 RedSocial
rectangle #08EFF3 Usuario
rectangle #CDEBA5 "BACKOFFICE ABIERTO" as OpenDashboard

admin --> ArtistaVista
note on link 
 crear artista (artista)
end note


ArtistaVista --> ArtistaControlador
note on link 
 crear artista (artista)
end note

ArtistaControlador --> ArtistaServicio
note on link 
 crear artista (artista)
end note


ArtistaServicio .-> RedSocialServicio
note on link 
 crear red social (red social)
end note

RedSocialServicio .-> RedSocialRepositorio
note on link 
 crear red social (red social)
end note

RedSocialRepositorio .-> RedSocial



ArtistaServicio .-> UsuarioServicio
note on link 
 crear usuario (usuario)
end note

UsuarioServicio .-> UsuarioRepositorio
note on link 
 crear usuario (usuario)
end note

UsuarioRepositorio .-> Usuario


ArtistaServicio --> ArtistaRepositorio
note on link 
 crear artista (artista)
end note

ArtistaRepositorio --> Artista
note on link 
 crear artista (artista)
end note

Artista --> ArtistaRepositorio
note on link 
 artista creado
end note

ArtistaRepositorio --> ArtistaServicio
note on link 
 artista creado
end note

ArtistaServicio --> ArtistaControlador
note on link 
 artista creado
end note

ArtistaControlador --> ArtistaVista
note on link 
 artista creado
end note

ArtistaVista -left-> OpenDashboard
note on link 
 artista creado
end note

@enduml
