@startuml login

skin rose
skinparam {
    NoteBorderThickness 0
    NoteBackgroundColor #whiteSmoke
    RectangleBackgroundColor #whiteSmoke
    ArchimateBackgroundColor #whiteSmoke
}

actor admin
rectangle #3CBE2D IniciarSesionVista
rectangle #629EF9 AccesoControlador
rectangle #C6480E AccesoServicio
rectangle #D269D2 AccesoRepository
rectangle #08EFF3 Acceso
rectangle #CDEBA5 "BACKOFFICE ABIERTO" as OpenDashboard

admin --> IniciarSesionVista

IniciarSesionVista --> AccesoControlador
note on link 
    acceso (usuario, contraseña)
end note

AccesoControlador -right-> AccesoServicio
note on link 
    acceso (usuario, contraseña)
end note


AccesoServicio -right-> AccesoRepository
note on link 
    acceso (usuario, contraseña)
end note


AccesoRepository -right-> Acceso 
note on link 
    buscar por usuario, contraseña
end note

Acceso --> AccesoRepository
note on link 
    acceso encontrado 
end note

AccesoRepository --> AccesoServicio
note on link 
    acceso encontrado 
end note

AccesoServicio --> AccesoControlador
note on link 
    acceso encontrado
end note

AccesoControlador --> IniciarSesionVista
note on link 
    Usuario logeado
end note

IniciarSesionVista -left-> OpenDashboard

@enduml
