<!--MD5=[93cd1932f4c096576fae441fe88ed719]
@startuml Controlladores

skin rose
skinparam {
    BoundaryBackgroundColor #629EF9
    BoundaryBorderColor black
    BoundaryFontSize 16
    BoundarySize 10
    BoundaryFontStyle bold
}
left to right direction

package Controladores {
    boundary AccesoControlador
    boundary AlbumControlador
    boundary ArtistaControlador
    boundary EmpresaControlador
    boundary EmpresaTipoControlador
    boundary ConciertoControlador
    boundary EmailControlador
    boundary ArtistaFestivalAsocControlador
    boundary FestivalControlador
    boundary RedSocialControlador
    boundary CancionControlador
    boundary UsuarioControlador
    boundary UsuarioTipoControlador
    boundary YoutubeVideoControlador
    boundary GenericoControlador

    GenericoControlador -up-|> AccesoControlador
    GenericoControlador -up-|> AlbumControlador
    GenericoControlador -up-|> ArtistaControlador
    GenericoControlador -up-|> EmpresaControlador
    GenericoControlador -up-|> EmpresaTipoControlador
    GenericoControlador -up-|> ConciertoControlador
    GenericoControlador --|> ArtistaFestivalAsocControlador
    GenericoControlador --|> FestivalControlador
    GenericoControlador --|> RedSocialControlador
    GenericoControlador --|> CancionControlador
    GenericoControlador --|> UsuarioControlador
    GenericoControlador --|> UsuarioTipoControlador
    GenericoControlador --|> YoutubeVideoControlador
}


@enduml
