@startuml entityladores

skin rose
skinparam {
    EntityBackgroundColor #08EFF3 
    EntityBorderColor black
    EntityFontSize 16
    EntitySize 10
    EntityFontStyle bold
}

left to right direction

package Modelos {
    entity Album
    entity Acceso
    entity Artista
    entity Empresa
    entity EmpresaTipo
    entity Concierto
    entity ArtistaFestivalAsoc
    entity Festival
    entity RedSocial
    entity Cancion
    entity Usuario
    entity UsuarioTipo
    entity YoutubeVideo
}

package entity {
    boundary hoal
}


UsuarioTipo --* Usuario
Acceso --* Usuario
EmpresaTipo --* Empresa

Cancion --* Artista
Album --* Artista
Concierto --* Artista
ArtistaFestivalAsoc --* Artista
RedSocial --* Artista

ArtistaFestivalAsoc --* Festival

Artista -- Usuario


@enduml
