@startuml databaseladores

skin rose
skinparam {
    DatabaseBackgroundColor #D269D2 
    DatabaseBorderColor black
    DatabaseFontSize 16
    DatabaseSize 10
    DatabaseFontStyle bold

    InterfaceBackgroundColor #DDD413
    InterfaceBorderColor black
    InterfaceFontSize 16
    InterfaceSize 10
    InterfaceFontStyle bold
}

left to right direction

package Repositorios {

    database AlbumRepositorio
    database AccesoRepositorio
    database ArtistaRepositorio
    database EmpresaRepositorio
    database EmpresaTipoRepositorio
    database ConciertoRepositorio
    database FestivalArtistaAsocRepositorio
    database FestivalRepositorio
    database RedSocialRepositorio
    database CancionRepositorio
    database UsuarioRepositorio
    database UsuarioTipoRepositorio
    database YoutubeVideoRepositorio
    database GenericoRepositorio

    interface IAlbumRepositorio 
    interface IAccesoRepositorio
    interface IArtistaRepositorio
    interface IEmpresaRepositorio
    interface IEmpresaTipoRepositorio
    interface IConciertoRepositorio
    interface IFestivalArtistaAsocRepositorio
    interface IFestivalRepositorio
    interface IRedSocialRepositorio
    interface ICancionRepositorio
    interface IUsuarioRepositorio
    interface IUsuarioTipoRepositorio
    interface IYoutubeVideoRepositorio
    interface IGenericoRepositorio

    AlbumRepositorio ..|> IAlbumRepositorio
    AccesoRepositorio ..|> IAccesoRepositorio
    ArtistaRepositorio ..|> IArtistaRepositorio
    EmpresaRepositorio ..|> IEmpresaRepositorio
    EmpresaTipoRepositorio ..|> IEmpresaTipoRepositorio
    ConciertoRepositorio ..|> IConciertoRepositorio
    FestivalArtistaAsocRepositorio ..|> IFestivalArtistaAsocRepositorio
    FestivalRepositorio .up.|> IFestivalRepositorio
    RedSocialRepositorio .up.|> IRedSocialRepositorio
    CancionRepositorio .up.|> ICancionRepositorio
    UsuarioRepositorio .up.|> IUsuarioRepositorio
    UsuarioTipoRepositorio .up.|> IUsuarioTipoRepositorio
    YoutubeVideoRepositorio .up.|> IYoutubeVideoRepositorio
    GenericoRepositorio .left.|> IGenericoRepositorio

    IGenericoRepositorio -up-|> IAlbumRepositorio
    IGenericoRepositorio -up-|> IAccesoRepositorio
    IGenericoRepositorio -up-|> IArtistaRepositorio
    IGenericoRepositorio -up-|> IEmpresaRepositorio
    IGenericoRepositorio -up-|> IEmpresaTipoRepositorio
    IGenericoRepositorio -up-|> IConciertoRepositorio
    IGenericoRepositorio -up-|> IFestivalArtistaAsocRepositorio
    IGenericoRepositorio --|> IFestivalRepositorio
    IGenericoRepositorio --|> IRedSocialRepositorio
    IGenericoRepositorio --|> ICancionRepositorio
    IGenericoRepositorio --|> IUsuarioRepositorio
    IGenericoRepositorio --|> IUsuarioTipoRepositorio
    IGenericoRepositorio --|> IYoutubeVideoRepositorio
}

@enduml
