<!--MD5=[93cd1932f4c096576fae441fe88ed719]
@startuml Vistas

skin rose
skinparam {
    cloudBackgroundColor #3CBE2D
    cloudBorderColor black
    cloudFontSize 16
    cloudSize 10
    CloudFontStyle bold
}
left to right direction

package Vistas {

    package PaginaWeb {
        cloud ListaNavegacionVista
        cloud PaginaPrincipalVista
        cloud MarketingVista
        cloud AgencyVista
        cloud VisualVista
        cloud TourManagerVista
        cloud DetallesArtistaVista
        cloud EmailVista
        cloud IniciarSesionVista
    }

    package Backoffice {
        cloud AlbumVista
        cloud ArtistaVista
        cloud EmpresaVista
        cloud ConciertoVista
        cloud ArtistaFestivalAsocVista
        cloud FestivalVista
        cloud RedSocialVista
        cloud CancionVista
        cloud UsuarioVista
        cloud YoutubeVideoVista
    }

    EmailVista --o PaginaPrincipalVista
    DetallesArtistaVista -left-o MarketingVista
    PaginaPrincipalVista --o ListaNavegacionVista
    MarketingVista --o ListaNavegacionVista
    AgencyVista -right-o ListaNavegacionVista
    VisualVista -left-o ListaNavegacionVista
    TourManagerVista -up-o ListaNavegacionVista

    RedSocialVista --o ArtistaVista
    ArtistaFestivalAsocVista --o FestivalVista
}

@enduml
